apiVersion: v1
kind: ConfigMap
metadata:
  name: appset-test-plugin
  namespace: argocd
data:
  token: '$appset-test-plugin:token'
  baseUrl: "http://appset-test-plugin.appset-test-plugin.svc.cluster.local"
