apiVersion: apps/v1
kind: Deployment
metadata:
  name: appset-test-plugin
  namespace: appset-test-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: appset-test-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: appset-test-plugin
    spec:
      containers:
        - name: appset-test-plugin
          image: quay.io/christianh814/appset-test-plugin:latest
          volumeMounts:
            - mountPath: /var/run/argo/token
              name: token
              subPath: token
      volumes:
        - name: token
          secret:
            secretName: appset-test-plugin