# This secret lives with the plugin, and is mounted into the plugin container. The ApplicationSet controller must be
# configured with the exact same secret.
apiVersion: v1
kind: Secret
metadata:
  name: appset-test-plugin
  namespace: appset-test-plugin
stringData:
  token: 'supersecret'
