apiVersion: v1
kind: Service
metadata:
  name: appset-test-plugin
  namespace: appset-test-plugin
spec:
  selector:
    app.kubernetes.io/name: appset-test-plugin
  ports:
  - name: http
    port: 8080
    targetPort: 8080
